version: '3' #versão do docker
services:
  website: #aplicação da web
    image: php:8.0-apache
    container_name:  webserver #pode mudar o nome 
    restart: always
    ports:
      - 8060:80 #mudar 8060 para porta que quiser
    volumes: #pasta onde o website está gravado
      -  path_to_code_folder :/var/www/html #muda aqui
  
  db:
    image: mysql:5.7 
    container_name: database #pode mudar o nome
    environment:
      MYSQL_ROOT_PASSWORD: password #mudar para mais segura
      MYSQL_DATABASE: db #mudar
      MYSQL_USER: user #mudar
      MYSQL_PASSWORD: password #mudar para mais segura
    volumes:
        - ./database/data:/docker-entrypoint-initdb.d #sincronização da database
  api:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin #pode mudar o nome
    environment:
        PMA_HOST: db
        PMA_PORT: 3306
    ports:
        - 8061:80 #mudar 8061 para porta que quiser